version: '3.6'

# Services
# Zookeeper, Kafka, Kafka Manager
services:
  zookeeper:
    image: 'zookeeper:latest'
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: 1

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - "9092:9092"
    environment:
      KAFKA_AVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOSTNAME: localhost
      ALLOW_PLAINTEXT_LISTENER: 1

  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "random-secret"

  flink-jobmanager:
    image: flink:latest
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager

  flink-taskmanager:
    image: flink:latest
    expose:
      - "6121"
    command: taskmanager
    links:
      - flink-jobmanager:jobmanager

  # telegraf, influxdb, grafana
  telegraf:
      image: telegraf:latest
      volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      links:
      - influxdb

  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: mydb
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_USER: user
      INFLUXDB_USER_PASSWORD: password

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ALLOW_EMBEDDING: "true"
    links:
      - influxdb
      - telegraf
