{
 "title": "Change detection",
 "time": { "from": "2023-12-18T07:28:35.024Z", "to": "2023-12-18T08:14:02.062Z" },
 "panels": [
  {
   "title": "Attacks and Accuracies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"mema_bucket\")\r\n  |> range(start: 2023-12-17T17:40:33Z, stop: 2023-12-17T18:16:25Z)\r\n  |> filter(fn: (r) => r._measurement == \"hai_results\" and r._field == \"attack\" or r._field == \"accuracy\")"
    }
   ]
  },
  {
   "title": "DDM results",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"mema_bucket\")\r\n  |> range(start: 2023-12-17T17:40:33Z, stop: 2023-12-17T18:16:25Z)\r\n  |> filter(fn: (r) => r._measurement == \"hai_results\" and r._field == \"accuracy\")"
    },
    {
     "query": "from(bucket: \"mema_bucket\")\r\n  |> range(start: 2023-12-17T17:40:33Z, stop: 2023-12-17T18:16:25Z)\r\n  |> filter(fn: (r) => r._measurement == \"hai_results\" and r._field == \"drift_detected\" and r._value > 0.5)"
    }
   ]
  },
  {
   "title": "Ratio of attacks",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mema_bucket\")\r\n  |> range(start: 2023-12-16T22:42:42Z, stop: 2023-12-16T22:43:44Z)\r\n  |> filter(fn: (r) => r._measurement == \"hai_input\" and r._field == \"attack\" and r._value < 0.5)\r\n  |> count(column: \"_value\")"
    },
    {
     "query": "from(bucket: \"mema_bucket\")\r\n  |> range(start: 2023-12-16T22:42:42Z, stop: 2023-12-16T22:43:44Z)\r\n  |> filter(fn: (r) => r._measurement == \"hai_input\" and r._field == \"attack\" and r._value > 0.5)\r\n  |> count(column: \"_value\")"
    }
   ]
  },
  {
   "title": "HDDM-W results",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"mema_bucket\")\r\n  |> range(start: 2023-12-17T20:16:00Z, stop: 2023-12-17T21:02:00Z)\r\n  |> filter(fn: (r) => r._measurement == \"hai_results\" and r._field == \"accuracy\")"
    },
    {
     "query": "from(bucket: \"mema_bucket\")\r\n  |> range(start: 2023-12-17T20:16:00Z, stop: 2023-12-17T21:02:00Z)\r\n  |> filter(fn: (r) => r._measurement == \"hai_results\" and r._field == \"drift_detected\" and r._value > 0.5)"
    }
   ]
  },
  {
   "title": "Ratio of attack types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mema_bucket\")\r\n  |> range(start: 2023-12-16T22:42:42Z, stop: 2023-12-16T22:43:44Z)\r\n  |> filter(fn: (r) => r._measurement == \"hai_input\" and r._field == \"attack_P1\" and r._value > 0.5)\r\n  |> count(column: \"_value\")"
    },
    {
     "query": "from(bucket: \"mema_bucket\")\r\n  |> range(start: 2023-12-16T22:42:42Z, stop: 2023-12-16T22:43:44Z)\r\n  |> filter(fn: (r) => r._measurement == \"hai_input\" and r._field == \"attack_P2\" and r._value > 0.5)\r\n  |> count(column: \"_value\")"
    },
    {
     "query": "from(bucket: \"mema_bucket\")\r\n  |> range(start: 2023-12-16T22:42:42Z, stop: 2023-12-16T22:43:44Z)\r\n  |> filter(fn: (r) => r._measurement == \"hai_input\" and r._field == \"attack_P3\" and r._value > 0.5)\r\n  |> count(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Basic Window DDM results",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"mema_bucket\")\r\n  |> range(start: 2023-12-17T21:15:00Z, stop: 2023-12-17T22:20:00Z)\r\n  |> filter(fn: (r) => r._measurement == \"hai_results\" and r._field == \"accuracy\")"
    },
    {
     "query": "from(bucket: \"mema_bucket\")\r\n  |> range(start: 2023-12-17T21:15:00Z, stop: 2023-12-17T22:10:00Z)\r\n  |> filter(fn: (r) => r._measurement == \"hai_results\" and r._field == \"drift_detected\" and r._value > 0.5)"
    }
   ]
  },
  {
   "title": "Cumsum of attacks with multi model drift detection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"mema_bucket\")\r\n  |> range(start: 2023-12-18T07:26:00Z, stop: 2023-12-18T08:14:00Z)\r\n  |> filter(fn: (r) => r._measurement == \"hai_results\" and r._field == \"attack\")\r\n  |> cumulativeSum(columns: [\"_value\"])"
    },
    {
     "query": "from(bucket: \"mema_bucket\")\r\n  |> range(start: 2023-12-18T07:26:00Z, stop: 2023-12-18T08:14:00Z)\r\n  |> filter(fn: (r) => r._measurement == \"hai_results\" and (r._field == \"attack\" or r._field == \"drift_detected\"))\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> cumulativeSum(columns: [\"attack\"])\r\n  |> map(fn: (r) => ({r with _value: r.attack + r.drift_detected}))\r\n  |> filter(fn: (r) => r.drift_detected == 1)\r\n  |> yield(name: \"cumulative_sum_with_points_and_filter\")\r\n"
    }
   ]
  },
  {
   "title": "Change detection with model selection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"mema_bucket\")\r\n  |> range(start: 2023-12-18T07:26:00Z, stop: 2023-12-18T08:14:00Z)\r\n  |> filter(fn: (r) => r._measurement == \"hai_results\" and r._field == \"accuracy\")"
    },
    {
     "query": "from(bucket: \"mema_bucket\")\r\n  |> range(start: 2023-12-18T07:26:00Z, stop: 2023-12-18T08:40:00Z)\r\n  |> filter(fn: (r) => r._measurement == \"hai_results\" and r._field == \"drift_detected\" and r._value > 0.5)"
    },
    {
     "query": "from(bucket: \"mema_bucket\")\r\n  |> range(start: 2023-12-18T07:26:00Z, stop: 2023-12-18T08:40:00Z)\r\n  |> filter(fn: (r) => r._measurement == \"hai_results\" and r._field == \"attack\")"
    }
   ]
  }
 ]
}